### ISSUE TITLE
Can't read video file

### ISSUE THREAD

**Issue by muschellij2** [ropensci/magick#215] opened 2019-08-03 18:34 UTC
Example where you cannot read the video.  It was rendered using ffmpeg.
[ari_test.mp4.zip](https://github.com/swarm-lab/Rvision/files/3464180/ari_test.mp4.zip)

``` r

destfile = tempfile(fileext = ".zip")
dl = download.file(
  "https://github.com/swarm-lab/Rvision/files/3464180/ari_test.mp4.zip",
  destfile)
tdir = tempfile()
dir.create(tdir)
path_to_video = unzip(destfile, exdir = tdir)

library(magick)
#> Linking to ImageMagick 6.9.9.39
#> Enabled features: cairo, fontconfig, freetype, lcms, pango, rsvg, webp
#> Disabled features: fftw, ghostscript, x11
xx = magick::image_read(path_to_video)
#> Error in magick_image_readpath(path, density, depth, strip): Magick: DelegateFailed `'ffmpeg' -nostdin -v -1 -vframes %S -i '%i' -vcodec pam -an -f rawvideo -y '%u.pam' 2> '%Z'' @ error/delegate.c/InvokeDelegate/1919
out_stub = file.path(tdir, "ffmpeg_test_%03d.png")
```

# Showing ffmpeg can convert to png

``` r
system2("ffmpeg", args = c("-i", path_to_video, out_stub))
Sys.sleep(4)
list.files(tdir)
#>  [1] "ari_test.mp4"        "ffmpeg_test_001.png" "ffmpeg_test_002.png"
#>  [4] "ffmpeg_test_003.png" "ffmpeg_test_004.png" "ffmpeg_test_005.png"
#>  [7] "ffmpeg_test_006.png" "ffmpeg_test_007.png" "ffmpeg_test_008.png"
#> [10] "ffmpeg_test_009.png" "ffmpeg_test_010.png" "ffmpeg_test_011.png"
#> [13] "ffmpeg_test_012.png" "ffmpeg_test_013.png" "ffmpeg_test_014.png"
#> [16] "ffmpeg_test_015.png" "ffmpeg_test_016.png" "ffmpeg_test_017.png"
#> [19] "ffmpeg_test_018.png" "ffmpeg_test_019.png" "ffmpeg_test_020.png"
#> [22] "ffmpeg_test_021.png" "ffmpeg_test_022.png" "ffmpeg_test_023.png"
#> [25] "ffmpeg_test_024.png" "ffmpeg_test_025.png" "ffmpeg_test_026.png"
#> [28] "ffmpeg_test_027.png" "ffmpeg_test_028.png" "ffmpeg_test_029.png"
#> [31] "ffmpeg_test_030.png" "ffmpeg_test_031.png" "ffmpeg_test_032.png"
#> [34] "ffmpeg_test_033.png" "ffmpeg_test_034.png" "ffmpeg_test_035.png"
#> [37] "ffmpeg_test_036.png" "ffmpeg_test_037.png" "ffmpeg_test_038.png"
#> [40] "ffmpeg_test_039.png" "ffmpeg_test_040.png" "ffmpeg_test_041.png"
#> [43] "ffmpeg_test_042.png" "ffmpeg_test_043.png" "ffmpeg_test_044.png"
#> [46] "ffmpeg_test_045.png" "ffmpeg_test_046.png" "ffmpeg_test_047.png"
#> [49] "ffmpeg_test_048.png" "ffmpeg_test_049.png" "ffmpeg_test_050.png"
#> [52] "ffmpeg_test_051.png" "ffmpeg_test_052.png" "ffmpeg_test_053.png"
#> [55] "ffmpeg_test_054.png" "ffmpeg_test_055.png" "ffmpeg_test_056.png"
#> [58] "ffmpeg_test_057.png" "ffmpeg_test_058.png" "ffmpeg_test_059.png"
```

<sup>Created on 2019-08-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.0 (2019-04-26)
#>  os       macOS Mojave 10.14.5        
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       America/New_York            
#>  date     2019-08-03                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package     * version date       lib source                           
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.0)                   
#>  backports     1.1.4   2019-04-10 [1] CRAN (R 3.6.0)                   
#>  callr         3.3.0   2019-07-04 [1] CRAN (R 3.6.0)                   
#>  cli           1.1.0   2019-03-19 [1] CRAN (R 3.6.0)                   
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.0)                   
#>  desc          1.2.0   2019-07-10 [1] Github (muschellij2/desc@b0c374f)
#>  devtools      2.1.0   2019-07-06 [1] CRAN (R 3.6.0)                   
#>  digest        0.6.20  2019-07-04 [1] CRAN (R 3.6.0)                   
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 3.6.0)                   
#>  fs            1.3.1   2019-05-06 [1] CRAN (R 3.6.0)                   
#>  glue          1.3.1   2019-03-12 [1] CRAN (R 3.6.0)                   
#>  highr         0.8     2019-03-20 [1] CRAN (R 3.6.0)                   
#>  htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.6.0)                   
#>  knitr         1.23    2019-05-18 [1] CRAN (R 3.6.0)                   
#>  magick      * 2.0     2018-10-05 [1] CRAN (R 3.6.0)                   
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.0)                   
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.0)                   
#>  pkgbuild      1.0.3   2019-03-20 [1] CRAN (R 3.6.0)                   
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.0)                   
#>  prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.6.0)                   
#>  processx      3.4.0   2019-07-03 [1] CRAN (R 3.6.0)                   
#>  ps            1.3.0   2018-12-21 [1] CRAN (R 3.6.0)                   
#>  R6            2.4.0   2019-02-14 [1] CRAN (R 3.6.0)                   
#>  Rcpp          1.0.2   2019-07-25 [1] CRAN (R 3.6.0)                   
#>  remotes       2.1.0   2019-06-24 [1] CRAN (R 3.6.0)                   
#>  rlang         0.4.0   2019-06-25 [1] CRAN (R 3.6.0)                   
#>  rmarkdown     1.13    2019-05-22 [1] CRAN (R 3.6.0)                   
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.0)                   
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.0)                   
#>  stringi       1.4.3   2019-03-12 [1] CRAN (R 3.6.0)                   
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.6.0)                   
#>  testthat      2.1.1   2019-04-23 [1] CRAN (R 3.6.0)                   
#>  usethis       1.5.1   2019-07-04 [1] CRAN (R 3.6.0)                   
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.0)                   
#>  xfun          0.8     2019-06-25 [1] CRAN (R 3.6.0)                   
#>  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.6.0)                   
#> 
#> [1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
```

</details>

**Comment by dmi3kno** [comment] 2019-08-04 20:49
Related to #160

**Comment by jeroen** [comment] 2019-08-04 23:47
Duplicate of https://github.com/ropensci/magick/issues/160

**Closed by jeroen** 2019-08-04 23:47 UTC

**Comment by jeroen** [comment] 2019-08-26 17:49
Magick 2.2 (on CRAN now) has `image_read_video()`.
