### ISSUE TITLE
No error when operation failed?

### ISSUE THREAD

**Issue by jzadra** [ropensci/magick#178] opened 2019-02-19 19:14 UTC
I am building a number of images using `for` loops to insert elements.  Somewhat regularly, imagemagick fails to do the operation in one or more loop iteration, leaving the graphic with a missing element.

I think this is due to memory issues (working on that in another thread) but for now what I need is to catch when this happens and retry.  However it seems that no error is generated when the operation fails.

How can I catch when the image wasn't modified, ie the image magick function didn't produce any result?  The `image_info()` looks the same before and after when it does do the function correctly so I can't compare on that.

**Comment by jeroen** [comment] 2019-02-19 21:22
Can you include an example of code that should error but does not?

**Comment by jzadra** [comment] 2019-02-19 21:27
The issue is code that should produce a result does not.  And unfortunately it's not replicable because it depends on memory limitations I think.

I have a loop that uses `image_composite()` to add a graphic in different locations, where each loop iteration is a different location.  Sometimes it will go through all 10 iterations, but for some reason the graphic that should have been composited on the 3rd iteration is missing - yet the following iterations are there.  If I run the code again, it will work.

But I'm not getting any error when the compositing doesn't work - it just passes the original image along - and so I can't detect when I"m missing an element other than visually inspecting each result.

**Comment by jeroen** [comment] 2019-02-19 22:18
This sounds like a bug but it's impossible to confirm without an example. Obviously it shouldn't happen, but perhaps imagemagick isn't properly accounting for out-of-memory situations.

**Comment by jzadra** [comment] 2019-02-19 23:28
I will see if I can come up with an example that uses a lot of memory and then try to replicate this.


Is there some way to compare an image to another, or the properties of an image?  I could create a before version and then see if it matches the after version (in which case I would have an indication of error).

**Comment by jeroen** [comment] 2019-02-20 00:31
Maybe `image_compare_dist` ?

**Comment by jzadra** [comment] 2019-02-26 00:44
Thanks.  I wrapped every single `magick` function with a while loop like this in pseudo code:

```
before <- image
while(image_compare_dist(before, image, metric = "AE") == 0) {
image <- image %>% magick::some_function()
}
```


I also put some informative output about when it was redoing the same function (ie ran through teh while loop more than once) and it happened quite frequently.  As you can imagine, since there are roughly 50 magick functions that occur even if they don't get repeated, added the while loop increased the processing time significantly since it has to do the image compare a minimum of 50 times (it's taken me about 4 days to generate roughly 3000 images), up from about 24 hours.

So, this is a decent temporary fix for anyone else experiencing this issue, but in the future if the memory issue isn't fixed, perhaps a check that the function succeeded would be good (ie replace my while loop).

**Comment by jeroen** [comment] 2019-07-20 11:20
Closing this due to lack of reproducible example. The expected behavior is indeed that magick rasies an error of an operation failed, so if this doesn't happen you need to give an example.

**Closed by jeroen** 2019-07-20 11:20 UTC
