### ISSUE TITLE
make it easier to specify geometry

### ISSUE THREAD

**Issue by jennybc** [ropensci/magick#18] opened 2016-08-24 18:22 UTC
Related to my apparently very confusing question on the [community call](https://github.com/ropensci/commcalls/issues/11).

Various operations require user to specify a location or region in the [Magick geometry specification](http://www.imagemagick.org/Magick++/Geometry.html), which is by default in pixels. This leads to lots of annoying arithmetic and trial and error for the user.

I was asking for ways to make this easier, such as:
1. specify a location relative to the image, e.g, seed the fill at c(0.5, 0.5) = middle of the image
2. overlay a grid or some sentinel points with pixel location indicated (like a football field)

As for point 1, it looks like the `%` geometry qualifier is very handy, so maybe worth featuring in docs or examples. Not sure if there's still room for `magick` to alleviate annoying arithmetic problems.

**Comment by jeroenooms** [comment] 2016-08-24 18:35
It doesn't look like this is included with magick++ itself. Most applications that build on magick++ expose some GUI to assist the user with this. We could easily write a javascript/shiny app which displays the figure and allows the user to click on a point or select a region and it would give the pixel coordinates, so you don't have to guess.

We could try to add logic on top with things like 'the center point' or 'right half' however there might be an almost infinite number of such concepts. And I prefer to keep the syntax close to what is used by the `imagemagick` command line utility.

**Comment by jennybc** [comment] 2016-08-24 18:53
OK that makes sense. Maybe just an example showing how user can use existing functionality to overlay those helpers in a quick and dirty way, get their pixels, and get on with things?

And/or arithmetic helper functions: image + user wish ("horizontal location 30% from left edge") goes in, pixel geometry comes out? I understand why you want to keep the syntax of the main function as close to command line API as possible. But a separate helper function might not muddy the waters too much. Feel free to close if none of this appeals.

**Comment by jennybc** [comment] 2016-08-24 19:02
Re: making sense from an R point of view: I am literally thinking of the way we specify location in the interval [0, 1] with something like `adj` or `vjust` or the way `npc` coordinates work in `grid`. Or the stuff you can do after a call of `par(usr=c(0,1,0,1))`.

**Comment by jeroenooms** [comment] 2016-08-24 19:22
R does seem to have a `locator(1)` and `identify` however it doesn't work too well...

**Comment by jeroen** [comment] 2017-08-04 12:13
Version 1.0 will feature a new `image_draw()` function which allows you to use the native graphics device to draw on top of the image. I think that might help with this use case.

**Comment by jeroen** [comment] 2017-11-25 18:30
Dupe of https://github.com/ropensci/magick/issues/82. Working on it :)

**Closed by jeroen** 2017-11-25 18:30 UTC
