### ISSUE TITLE
Inline rendering in RMarkdown documents

### ISSUE THREAD

**Issue by dhmontgomery** [ropensci/magick#102] opened 2017-12-28 21:59 UTC
When creating a normal graphic in RMarkdown — such as a ggplot graph — it displays inline, below the code chunk that produced the image.

But if a `magick` image is created in RMarkdown — such as my normal use case, taking a ggplot graphic, resizing and adding a logo — then it inline only displays a text output like this: 

```
  format width height colorspace matte filesize
1    PNG  2029   1140       sRGB FALSE        0
```

And outputs the image itself to RStudio's plots pane. 

It would be nice if `magick` graphics could display inline in RMarkdown documents. (As of a recent update, they CAN display when RMarkdown documents are knit. But they don't display in the document itself.)

**Comment by jeroen** [comment] 2017-12-28 23:42
I don't understand how you are using rmarkdown. AFAIK rmarkdown always knits the document first?

**Comment by dhmontgomery** [comment] 2017-12-28 23:47
Before you click knit and generate a report, you can write and execute code in RMarkdown. If you do, it displays your generated images (or tibbles) in the .Rmd file, even before you've generated a PDF or HTML or other file through knitting. It's this that doesn't generate inline through `magick`:

<img width="909" alt="screenshot 2017-12-28 17 45 09" src="https://user-images.githubusercontent.com/12974539/34425937-f769026c-ebf6-11e7-80a3-208d04f67da2.png">

**Comment by jeroen** [comment] 2017-12-28 23:54
OK I'll ask the rstudio folks how to hook this up to the notebooks.

**Comment by dhmontgomery** [comment] 2017-12-29 00:00
Notebooks! That's the term that was escaping me.

**Comment by jeroen** [comment] 2019-07-24 14:31
Dupe of https://github.com/ropensci/magick/issues/114

**Closed by jeroen** 2019-07-24 14:31 UTC
