### ISSUE TITLE
Is it possible to print bold text with image_annotate()?

### ISSUE THREAD

**Issue by smonsays** [ropensci/magick#104] opened 2018-01-15 10:32 UTC
I would like to print bold text to an image using `image_annotate()`, but I couldn't find anything in the documentation in this direction. Is there currently a way to do this?

**Comment by jeroen** [comment] 2018-01-15 10:57
It is easier to do this with `image_draw ()` and then use base `text ()`

**Comment by smonsays** [comment] 2018-01-15 11:28
Yes, that is my workaround as well. Still, I would prefer to use `image_annotate()` as it behaves more consistent and user-friendly when it comes to properly position the text. 

Any chance that this feature could be added? I took a look at the Magick++ STL but couldn't find anything too promising in this regard..

**Comment by jeroen** [comment] 2018-09-30 21:48
Dupe of https://github.com/ropensci/magick/issues/113

**Closed by jeroen** 2018-09-30 21:48 UTC
