### ISSUE TITLE
Error from image_deskew(): Magick: TIFF: negative image positions unsupported

### ISSUE THREAD

**Issue by ShirinG** [ropensci/magick#56] opened 2017-07-12 15:06 UTC
I am using magick to prepare images for tesseract's ocr() function (rOpenSci package) and with some images I get the following error when I also used image_deskew(): Magick: TIFF: negative image positions unsupported.

The possible solution (using repage) seems to not be implemented?

Thank you!

**Comment by jeroen** [comment] 2017-07-24 11:29
Could you add some example code? What does repage do?

**Comment by ShirinG** [comment] 2017-07-24 11:43
It removes/resets the virtual canvas meta-data from the images.

I've read that it solves the solution here: https://www.imagemagick.org/discourse-server/viewtopic.php?t=25961

**Comment by jeroen** [comment] 2017-08-02 13:15
Do you have an example image/code that I can use to test this?

**Comment by jeroen** [comment] 2017-08-02 13:16
I also added an `magick::image_ocr()` wrapper.

**Comment by ShirinG** [comment] 2017-08-03 06:02
Sure, this is the image: [https://github.com/ShirinG/blog_posts_prep/blob/master/ocr/beispiel_scan.png](https://github.com/ShirinG/blog_posts_prep/blob/master/ocr/beispiel_scan.png)

And the code:
`
library(tidyverse)
library(tesseract)
library(magick)

image <- image_read("beispiel_scan.png")

image_bearb <- image %>%
  image_scale("x2000") %>%                        # rescale
  image_background("white", flatten = TRUE) %>%   # set background to white
  image_trim() %>%                                # Trim edges that are the background color from the image.
  image_noise() %>%                               # Reduce noise in image using a noise peak elimination filter.
  image_enhance() %>%                             # Enhance image (minimize noise)
  image_normalize() %>%                           # Normalize image (increase contrast by normalizing the pixel values to span the full range of color values).
  image_contrast(sharpen = 1) %>%                 # increase contrast
  image_deskew(treshold = 40)                     # deskew image -> creates negative offset in some scans == error

text_2 <- ocr(image_bearb,
              engine = tesseract(language = "deu"))
`

**Comment by jeroen** [comment] 2017-08-03 08:04
Hmm it could actually be a problem with the dictionary. Do you get the same error if you don't set the `language` parameter?

**Comment by ShirinG** [comment] 2017-08-03 08:07
Yes, I do get the same error when I use

`
text_2 <- ocr(image_bearb)
`

**Comment by jeroen** [comment] 2017-08-03 08:19
Hmm I can't reproduce the problem here. But it is probably caused by the fact that I use `tiff` to get the image from magick to tesseract format but maybe I should change that. 

Could you try if the problem disappears when you save as png instead?

```
image_write(image_bearb, "test.png", format = "png")
tesseract::ocr("test.png", engine = tesseract(language = "deu"))
```

**Comment by ShirinG** [comment] 2017-08-03 08:26
Yeah, this works. So, there is no way to have one consecutive pipeline for the whole analysis?

**Comment by jeroen** [comment] 2017-08-03 08:29
It will be fixed in the next version.

**Comment by ShirinG** [comment] 2017-08-03 08:52
Thank you!

**Comment by jeroen** [comment] 2017-08-15 12:08
This should be fixed in the new version on CRAN. 

Note that the `magick` package now also has a convenience wrapper for tesseract so you can pipe to `image_ocr()`

**Closed by jeroen** 2017-08-15 12:08 UTC
